services:
  postgres_master:
    image: citusdata/citus:latest
    container_name: postgres_master
    environment:
      POSTGRES_DB: ${DB_NAME_MASTER}
      POSTGRES_USER: ${DB_USER_MASTER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_MASTER}
      PGPASSWORD: pass
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_MASTER}:5432
    volumes:
      - ./pg_data/master/:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=citus"]
    networks:
      shared-net:
        aliases:
          - postgres_master.shared
    hostname: postgres_master
    env_file: ".env"
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command:
      - '--appendonly'
      - 'yes'
      - '--save'
      - '60 10'
    environment:
      - REDIS_PASSWORD=123123vv
      - REDIS_LRU_LIMIT_MB=1024
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    networks:
      shared-net:
        aliases:
          - rabbitmq.shared
    hostname: rabbitmq
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      #  Crucially, create a new user for production
      RABBITMQ_NODE_PORT: 5672
      RABBITMQ_NODE_NAME: mynode
      RABBITMQ_USER: myuser
      RABBITMQ_PASS: mystrongpassword
      RABBITMQ_USE_TLS: false
  app:
    container_name: app_socnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      shared-net:
        aliases:
          - app.shared
    hostname: app
    depends_on:
      - postgres_master
    env_file:
      - .env

networks:
  shared-net:
    external: true
    name: shared-app-network
