services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-elru
    ports:
      - ${PORT}:3101
    volumes:
      - ./app:/var/www/electric_ru_symfony
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: ".env"

  php82:
    container_name: php82-elru
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    volumes:
      - ./app/.env:/var/www/electric_ru_symfony/.env
    env_file: ".env"

  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres-elru
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Europe/Moscow
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    env_file: ".env"
