services:
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx-social-network
  #   ports:
  #     - ${NGINX_PORT}:80
  #   volumes:
  #     - ./app:/var/www/social_network
  #     - ./config/nginx/default.conf.template:/etc/nginx/conf.d/default.conf
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   env_file: ".env"

  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres-soc-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    env_file: ".env"
