services:
  postgres_master:
    image: postgres:16.1-alpine3.18
    container_name: postgres_master
    environment:
      POSTGRES_DB: ${DB_NAME_MASTER}
      POSTGRES_USER: ${DB_USER_MASTER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_MASTER}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_MASTER}:5432
    volumes:
      - ./config/postgres/master/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./config/postgres/master/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_data/master/:/var/lib/postgresql/data
    networks:
      otus-network:
        ipv4_address: "172.33.0.3"
    env_file: ".env"
  postgres_slave_sync:
    image: postgres:16.1-alpine3.18
    container_name: postgres_slave_sync
    environment:
      POSTGRES_DB: ${DB_NAME_SLAVE_1}
      POSTGRES_USER: ${DB_USER_SLAVE_1}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SLAVE_1}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_SLAVE_1}:5432
    volumes:
      - ./config/postgres/slave_sync/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_data/pgslave:/var/lib/postgresql/data
    depends_on:
      - postgres_master
    networks:
      otus-network:
        ipv4_address: "172.33.0.4"
    env_file: ".env"
  postgres_slave_async:
    image: postgres:16.1-alpine3.18
    container_name: postgres_slave_async
    environment:
      POSTGRES_DB: ${DB_NAME_SLAVE_2}
      POSTGRES_USER: ${DB_USER_SLAVE_2}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SLAVE_2}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_SLAVE_2}:5432
    volumes:
      - ./config/postgres/slave_async/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_data/pgasyncslave:/var/lib/postgresql/data
    depends_on:
      - postgres_master
    networks:
      otus-network:
        ipv4_address: "172.33.0.5"
    env_file: ".env"

  app:
    container_name: app_socnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      otus-network:
        ipv4_address: "172.33.0.2"
    depends_on:
      - postgres_master
      - postgres_slave_sync
      - postgres_slave_async
    env_file:
      - .env

networks:
  otus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/24
