services:
  postgres_master:
    image: postgres:16.1-alpine3.18
    container_name: postgres_master
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_MASTER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_MASTER}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_MASTER}:5432
    volumes:
      - ./db_data_master:/var/lib/postgresql/data
    networks:
      otus-network:
        ipv4_address: "172.33.0.3"
    env_file: ".env"
  postgres_slave_1:
    image: postgres:16.1-alpine3.18
    container_name: postgres_slave_1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_SLAVE_1}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SLAVE_1}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_SLAVE_1}:5432
    networks:
      otus-network:
        ipv4_address: "172.33.0.4"
    env_file: ".env"
  postgres_slave_2:
    image: postgres:16.1-alpine3.18
    container_name: postgres_slave_2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_SLAVE_2}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SLAVE_2}
      TZ: Europe/Moscow
    ports:
      - ${DB_PORT_SLAVE_2}:5432
    networks:
      otus-network:
        ipv4_address: "172.33.0.5"
    env_file: ".env"

  app:
    container_name: app_socnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      otus-network:
        ipv4_address: "172.33.0.2"
    depends_on:
      - postgres_master
      - postgres_slave_1
      - postgres_slave_2
    env_file:
      - .env

networks:
  otus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/24
